import { useEffect, useRef, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { api } from '../engine/api';
import type { Presentation, CommandLog, SlideObject } from '../types/presentation';
import SlideCanvas from '../components/SlideCanvas';
import VoiceCommandBar from '../components/VoiceCommandBar';

const uid=(prefix:string)=>`${prefix}_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;
const defaultStyle=(type:string):any=>({x:80,y:140,w:type==='image'?420:1000,h:type==='image'?280:80,rotation:0,fontSize:type==='title'?40:20,bold:type==='title',italic:false,underline:false,color:'#f5f5f7',align:'left',zIndex:10,hidden:false,highlighted:false,zoom:1});

export default function Editor(){
 const {id}=useParams(); const navigate=useNavigate();
 const [presentation,setPresentation]=useState<Presentation|null>(null); const [currentSlideId,setCurrentSlideId]=useState(''); const [selectedObjectId,setSelectedObjectId]=useState<string|null>(null);
 const [logs,setLogs]=useState<CommandLog[]>([]); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [versions,setVersions]=useState<any[]>([]); const [notesLoading,setNotesLoading]=useState(false); const [search,setSearch]=useState(''); const [showAdd,setShowAdd]=useState(false); const saveTimer=useRef<any>(null); const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{if(!id)return; api.getPresentation(id).then(p=>{setPresentation(p);setCurrentSlideId(p.slides[0]?.id||'')}).catch(e=>setError(e.message)); api.listVersions(id).then(setVersions).catch(()=>{});},[id]);
 function updatePresentation(p:Presentation,autosave=true){p.updatedAt=new Date().toISOString();setPresentation({...p});if(autosave){setSaving(true);clearTimeout(saveTimer.current);saveTimer.current=setTimeout(()=>api.savePresentation(p).finally(()=>setSaving(false)),350)}}
 if(!presentation)return <div style={{padding:40,color:'var(--text-dim)'}}>{error||'Loading…'}</div>;
 const slide=presentation.slides.find(s=>s.id===currentSlideId)||presentation.slides[0]; const selectedObj=slide.objects.find(o=>o.id===selectedObjectId)||null;
 function clone(){return JSON.parse(JSON.stringify(presentation)) as Presentation}
 function addSlide(){const p=clone();const idx=p.slides.length+1;const s:any={id:uid('slide'),index:idx,layout:'standard',background:'#0b0b0d',speakerNotes:'',transition:'fade',objects:[{id:uid(`slide${idx}_title`),type:'title',content:'New Slide',data:{},style:{...defaultStyle('title'),x:60,y:50,w:1100,h:90}}]};p.slides.push(s);updatePresentation(p);setCurrentSlideId(s.id);setSelectedObjectId(s.objects[0].id)}
 function deleteSlide(sid:string){if(presentation.slides.length<=1)return;const p=clone();p.slides=p.slides.filter(s=>s.id!==sid).map((s,i)=>({...s,index:i+1}));updatePresentation(p);if(currentSlideId===sid)setCurrentSlideId(p.slides[0].id)}
 function updateObj(next:SlideObject){const p=clone();const s=p.slides.find(s=>s.id===currentSlideId)!;const i=s.objects.findIndex(o=>o.id===next.id);if(i>=0)s.objects[i]=next;updatePresentation(p)}
 function addObject(type:'text'|'shape'|'image'){const p=clone();const s=p.slides.find(s=>s.id===currentSlideId)!;const n=s.objects.length+1;const obj:any={id:uid(`slide${s.index}_${type}`),type,content:type==='text'?'New text':'',data:type==='shape'?{shape:'rounded-rectangle'}:{},style:{...defaultStyle(type),zIndex:n}};s.objects.push(obj);updatePresentation(p);setSelectedObjectId(obj.id);setShowAdd(false)}
 function addImage(file:File){const reader=new FileReader();reader.onload=()=>{const p=clone();const s=p.slides.find(s=>s.id===currentSlideId)!;const obj:any={id:uid(`slide${s.index}_image`),type:'image',content:file.name,data:{src:String(reader.result),crop:{x:0,y:0,w:100,h:100}},style:{...defaultStyle('image'),zIndex:s.objects.length+1}};s.objects.push(obj);updatePresentation(p);setSelectedObjectId(obj.id)};reader.readAsDataURL(file)}
 function updateField(field:string,value:any){if(!selectedObj)return;const next=clone();const s=next.slides.find(s=>s.id===currentSlideId)!;const o=s.objects.find(o=>o.id===selectedObj.id)!;(o.style as any)[field]=value;updatePresentation(next)}
 function updateCrop(field:string,value:number){if(!selectedObj||selectedObj.type!=='image')return;const next=clone();const s=next.slides.find(s=>s.id===currentSlideId)!;const o=s.objects.find(o=>o.id===selectedObj.id)!;o.data.crop={x:Number(o.data.crop?.x||0),y:Number(o.data.crop?.y||0),w:Number(o.data.crop?.w||100),h:Number(o.data.crop?.h||100),[field]:value};if(field==='w')o.data.crop.w=Math.max(10,Math.min(100-value,o.data.crop.w));if(field==='h')o.data.crop.h=Math.max(10,Math.min(100-value,o.data.crop.h));updatePresentation(next)}
 async function generateNotes(){if(!id)return;setNotesLoading(true);try{const {speakerNotes}=await api.generateSpeakerNotes(id,currentSlideId);const p=clone();p.slides.find(s=>s.id===currentSlideId)!.speakerNotes=speakerNotes;updatePresentation(p)}catch(e:any){setError(e.message)}finally{setNotesLoading(false)}}
 function runSearch(){if(!search.trim())return;api.sendCommand({presentationId:presentation.id,currentSlideId,transcript:`find slides mentioning ${search}`}).then(res=>{setLogs(res.logs||[]);if(res.searchResults?.length)setCurrentSlideId(res.searchResults[0])})}
 function manual(cmd:string){api.sendCommand({presentationId:presentation.id,currentSlideId,selectedObjectId,transcript:cmd}).then(res=>{setPresentation(res.presentation);setLogs(res.logs||[])})}
 return <div style={{display:'grid',gridTemplateColumns:'220px 1fr 330px',height:'100vh'}}>
  <div style={{borderRight:'1px solid var(--border)',overflowY:'auto',padding:12}}>
   <button className="btn btn-ghost" style={{width:'100%',marginBottom:10}} onClick={()=>navigate('/select')}>← Home</button>
   <button className="btn" style={{width:'100%',marginBottom:8}} onClick={addSlide}>+ Add slide</button>
   <button className="btn btn-primary" style={{width:'100%',marginBottom:12}} onClick={()=>fileRef.current?.click()}>＋ Add image</button>
   <input ref={fileRef} type="file" accept="image/*" hidden onChange={e=>{const f=e.target.files?.[0];if(f)addImage(f);e.currentTarget.value=''}}/>
   {presentation.slides.map(s=><div key={s.id} onClick={()=>{setCurrentSlideId(s.id);setSelectedObjectId(null)}} style={{padding:10,borderRadius:8,marginBottom:8,cursor:'pointer',border:s.id===currentSlideId?'1px solid var(--accent)':'1px solid var(--border)',background:s.id===currentSlideId?'rgba(110,231,255,.06)':'var(--graphite)',fontSize:12}}><div style={{display:'flex',justifyContent:'space-between'}}><span>Slide {s.index}</span>{presentation.slides.length>1&&<span style={{color:'var(--danger)'}} onClick={e=>{e.stopPropagation();deleteSlide(s.id)}}>✕</span>}</div><div style={{color:'var(--text-dim)',marginTop:4,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{s.objects.find(o=>o.type==='title')?.content||'(untitled)'}</div></div>)}
  </div>
  <div style={{display:'flex',flexDirection:'column',overflow:'hidden'}}>
   <div style={{padding:'12px 20px',borderBottom:'1px solid var(--border)',display:'flex',alignItems:'center',gap:10}}>
    <input className="input" style={{maxWidth:300,fontWeight:600}} value={presentation.title} onChange={e=>updatePresentation({...presentation,title:e.target.value})}/><span style={{fontSize:12,color:'var(--text-dim)'}}>{saving?'Saving…':'Saved'}</span><div style={{flex:1}}/>
    <input className="input" placeholder="Search slides…" style={{maxWidth:190}} value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&runSearch()}/>
    <button className="btn" onClick={()=>setShowAdd(v=>!v)}>＋ Object</button><button className="btn" onClick={()=>id&&api.saveVersion(id,'Manual save').then(()=>api.listVersions(id).then(setVersions))}>Save version</button><ExportMenu id={id!}/><button className="btn btn-primary" onClick={()=>navigate(`/presenter/${id}`)}>Present ▶</button>
   </div>
   {showAdd&&<div style={{padding:'8px 20px',borderBottom:'1px solid var(--border)',display:'flex',gap:8}}><button className="btn" onClick={()=>addObject('text')}>Text</button><button className="btn" onClick={()=>addObject('shape')}>Shape</button><button className="btn" onClick={()=>fileRef.current?.click()}>Image</button></div>}
   <div style={{flex:1,overflow:'auto',display:'flex',alignItems:'center',justifyContent:'center',padding:24}}>{slide&&<SlideCanvas slide={slide} selectedObjectId={selectedObjectId} onSelect={setSelectedObjectId} onObjectChange={updateObj} scale={0.75}/>}</div>
   <div style={{padding:12,borderTop:'1px solid var(--border)'}}><VoiceCommandBar presentation={presentation} currentSlideId={currentSlideId} selectedObjectId={selectedObjectId} onUpdate={p=>updatePresentation(p,false)} onLogs={setLogs}/>{logs.length>0&&<div style={{marginTop:8,fontSize:11,color:'var(--text-dim)',maxHeight:70,overflow:'auto'}}>{logs.slice(-5).map((l,i)=><div key={i}>→ <b>{l.intent}</b>: {l.message}</div>)}</div>}</div>
  </div>
  <div style={{borderLeft:'1px solid var(--border)',overflowY:'auto',padding:16}}>
   <div style={{fontWeight:700,marginBottom:12}}>Inspector</div>
   {selectedObj?<div style={{display:'grid',gap:10}}>
    <div style={{fontSize:11,color:'var(--text-dim)',wordBreak:'break-all'}}>{selectedObj.id} · {selectedObj.type}</div>
    {(selectedObj.type==='title'||selectedObj.type==='subtitle'||selectedObj.type==='text')&&<textarea className="input" rows={4} value={selectedObj.content} onChange={e=>{const n=JSON.parse(JSON.stringify(selectedObj));n.content=e.target.value;updateObj(n)}}/>}
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:6}}><Num label="X" value={selectedObj.style.x} onChange={v=>updateField('x',v)}/><Num label="Y" value={selectedObj.style.y} onChange={v=>updateField('y',v)}/><Num label="W" value={selectedObj.style.w} onChange={v=>updateField('w',v)}/><Num label="H" value={selectedObj.style.h} onChange={v=>updateField('h',v)}/><Num label="Rotate" value={selectedObj.style.rotation} onChange={v=>updateField('rotation',v)}/><Num label="Zoom" value={selectedObj.style.zoom||1} step={0.1} onChange={v=>updateField('zoom',v)}/></div>
    {(selectedObj.type==='title'||selectedObj.type==='subtitle'||selectedObj.type==='text'||selectedObj.type==='bullet_list')&&<div className="card" style={{padding:10}}><div style={{fontWeight:700,fontSize:12,marginBottom:8}}>Text & point styling</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:6}}><Num label="Font size" value={selectedObj.style.fontSize} onChange={v=>updateField('fontSize',Math.max(8,Math.min(120,v)))}/><label>Color<input className="input" type="color" value={selectedObj.style.color||'#f5f5f7'} onChange={e=>updateField('color',e.target.value)}/></label></div><div style={{display:'flex',gap:6,flexWrap:'wrap',marginTop:8}}><button className={`btn ${selectedObj.style.bold?'btn-primary':''}`} onClick={()=>updateField('bold',!selectedObj.style.bold)}>Bold</button><button className={`btn ${selectedObj.style.italic?'btn-primary':''}`} onClick={()=>updateField('italic',!selectedObj.style.italic)}>Italic</button><button className={`btn ${selectedObj.style.underline?'btn-primary':''}`} onClick={()=>updateField('underline',!selectedObj.style.underline)}>Underline</button><select className="input" style={{width:120}} value={selectedObj.style.align||'left'} onChange={e=>updateField('align',e.target.value)}><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option><option value="justify">Justify</option></select></div><div style={{fontSize:11,color:'var(--text-dim)',marginTop:7}}>These controls apply to the selected heading, paragraph, or all points in the selected bullet block.</div></div>}
    {selectedObj.type==='bullet_list'&&<textarea className="input" rows={6} placeholder="One point per line" value={(selectedObj.data?.items||[]).join('\n')} onChange={e=>{const n=JSON.parse(JSON.stringify(selectedObj));n.data={...(n.data||{}),items:e.target.value.split(/\n/).filter(Boolean)};updateObj(n)}}/>}
    <div style={{display:'flex',gap:6,flexWrap:'wrap'}}><button className="btn" onClick={()=>manual(selectedObj.style.highlighted?'unhighlight':'highlight')}>{selectedObj.style.highlighted?'Unhighlight':'Highlight'}</button><button className="btn" onClick={()=>manual(selectedObj.style.hidden?'show':'hide')}>{selectedObj.style.hidden?'Show':'Hide'}</button><button className="btn" onClick={()=>manual('duplicate this')}>Duplicate</button><button className="btn" onClick={()=>manual('delete this')}>Delete</button></div>
    {selectedObj.type==='image'&&<div className="card" style={{padding:10}}><div style={{fontWeight:700,fontSize:12,marginBottom:8}}>Image crop</div><Range label="Crop left" value={selectedObj.data.crop?.x||0} onChange={v=>updateCrop('x',v)}/><Range label="Crop top" value={selectedObj.data.crop?.y||0} onChange={v=>updateCrop('y',v)}/><Range label="Crop width" value={selectedObj.data.crop?.w||100} onChange={v=>updateCrop('w',v)} min={10}/><Range label="Crop height" value={selectedObj.data.crop?.h||100} onChange={v=>updateCrop('h',v)} min={10}/><div style={{fontSize:11,color:'var(--text-dim)',marginTop:6}}>Drag the image to place it. Drag the blue corner handle to resize. Voice commands can also control it.</div></div>}
   </div>:<div style={{fontSize:13,color:'var(--text-dim)'}}>Select any object. Images are real editable objects, not flattened placeholders.</div>}
   <div style={{marginTop:22}}><div style={{fontWeight:700,marginBottom:8}}>Speaker notes</div><textarea className="input" rows={5} value={slide?.speakerNotes||''} onChange={e=>{const p=clone();p.slides.find(s=>s.id===currentSlideId)!.speakerNotes=e.target.value;updatePresentation(p)}}/><button className="btn" style={{marginTop:8,width:'100%'}} onClick={generateNotes} disabled={notesLoading}>{notesLoading?'Generating…':'✨ Generate with AI'}</button></div>
   {versions.length>0&&<div style={{marginTop:22}}><div style={{fontWeight:700,marginBottom:8}}>Version history</div>{versions.map(v=><div key={v.id} style={{fontSize:11,color:'var(--text-dim)',padding:'6px 0',borderBottom:'1px solid var(--border)',display:'flex',justifyContent:'space-between'}}><span>{new Date(v.created_at).toLocaleString()}</span><span style={{color:'var(--accent)',cursor:'pointer'}} onClick={()=>api.restoreVersion(id!,v.id).then(p=>{setPresentation(p);setCurrentSlideId(p.slides[0]?.id||'')})}>Restore</span></div>)}</div>}
  </div>
 </div>
}
function Num({label,value,onChange,step=1}:{label:string,value:number,onChange:(n:number)=>void,step?:number}){return <label style={{fontSize:10,color:'var(--text-dim)'}}>{label}<input className="input" type="number" step={step} value={Number.isFinite(value)?value:0} onChange={e=>onChange(Number(e.target.value))}/></label>}
function Range({label,value,onChange,min=0,max=100}:{label:string,value:number,onChange:(n:number)=>void,min?:number,max?:number}){return <label style={{display:'block',fontSize:10,color:'var(--text-dim)',marginBottom:6}}>{label}<input style={{width:'100%'}} type="range" min={min} max={max} value={value} onChange={e=>onChange(Number(e.target.value))}/><span>{Math.round(value)}%</span></label>}
function ExportMenu({id}:{id:string}){const [open,setOpen]=useState(false);return <div style={{position:'relative'}}><button className="btn" onClick={()=>setOpen(v=>!v)}>Export ▾</button>{open&&<div style={{position:'absolute',top:40,right:0,background:'var(--graphite)',border:'1px solid var(--border)',borderRadius:10,padding:8,zIndex:30,width:170}}>{(['pptx','pdf','transcript','json'] as const).map(k=><a key={k} href={api.exportUrl(id,k)} style={{display:'block',padding:'8px 10px',fontSize:13}}>{k.toUpperCase()}</a>)}</div>}</div>}
